export const reportDisplayFields = [
    { key: "report_date", label: "日付" },
    { key: "worker_name", label: "名前" },
    { key: "site_name", label: "現場名" },
    { key: "shift_type", label: "区分" },
    { key: "start_time", label: "開始時間" },
    { key: "end_time", label: "終了時間" },
    { key: "worker_count", label: "稼働人数" },
    { key: "vehicle_count", label: "車両台数" },
    { key: "driver_name", label: "車両運転手" },
    { key: "expressway_main", label: "高速料金（本体）" },
    { key: "expressway_secondary", label: "高速料金（二次受け）" },
    { key: "expressway_subcontract", label: "高速料金（下請け）" },
    { key: "parking_main", label: "駐車場料金（本体）" },
    { key: "parking_secondary", label: "駐車場料金（二次受け）" },
    { key: "parking_subcontract", label: "駐車場料金（下請け）" },
    { key: "fuel_gasoline", label: "燃料代（ガソリン）" },
    { key: "fuel_diesel", label: "燃料代（軽油）" },
    { key: "members", label: "メンバー" },
    { key: "work_description", label: "作業内容" },
    { key: "note", label: "備考" },
  ] as const;